// Generated by CoffeeScript 1.3.1
(function() {
  var log, users, util;

  util = require('../lib/util');

  users = [
    {
      uid: 0,
      name: 'Nicholas Hallahan',
      email: 'nick@theoutpost.io'
    }, {
      uid: 1,
      name: 'Jeddy'
    }, {
      uid: 2,
      email: 'test3@domaindomain.com'
    }, {
      uid: 3,
      name: 'Jennifer Tabetha \"The Elbow\" Weineki-Warren',
      email: 'jennifer.tabetha.the.elbow.weineki.warren@gmail.com'
    }, {
      uid: 4,
      name: 'Olaf Gustafssonn',
      email: 'oly3321@hotmail.com'
    }, {
      uid: 5,
      name: 'Gandhi',
      email: 'indianmystic@obe.co.uk'
    }
  ];

  log = [
    {
      lid: 0,
      uid: 5,
      time: new Date(2001, 6, 6, 6, 6, 6).getTime(),
      text: 'An Englishman named O.E Woodhouse won the singles title'
    }, {
      lid: 1,
      uid: 4,
      time: new Date(2001, 6, 6, 6, 7, 6).getTime(),
      text: 'Camp Washington'
    }, {
      lid: 2,
      uid: 0,
      time: new Date(2001, 6, 6, 7, 6, 7).getTime(),
      text: 'In December 1873, Major Walter Clopton Wingfield designed and patented a similar game – which he called sphairistike (Greek: σφάίρίστική, from ancient Greek meaning "skill at playing at ball"), and was soon known simply as "sticky" — for the amusement of his guests at a garden party on his estate of Nantclwyd, in Llanelidan, Wales.[12] Sport historians agree that Wingfield deserves much of the credit for the development of modern tennis.[8][13] The world oldest tennis tournament, the Wimbledon championships, were first played in London in 1877.[14][15] The first Championships culminated a significant debate on how to standardize the rules.'
    }, {
      lid: 3,
      uid: 0,
      time: new Date(2012, 4, 4, 9, 6, 6).getTime(),
      text: 'Between 1859 and 1865 Harry Gem and his friend Augurio Perera developed a game that combined elements of rackets and the Basque ball game pelota, which they played on Pereras croquet lawn in Birmingham, United Kingdom.[9][10] In 1872, along with two local doctors, they founded the worlds first tennis club in Leamington Spa.'
    }, {
      lid: 4,
      uid: 3,
      time: new Date(2012, 4, 16, 9, 6, 6).getTime(),
      text: 'Two exceptions are that from 1908 to 1961 the server had to keep one foot on the ground at all times, and the adoption of the tie-break in the 1970s.'
    }, {
      lid: 5,
      uid: 2,
      time: new Date(2012, 4, 16, 9, 7, 6).getTime(),
      text: 'Tennis is enjoyed by millions.'
    }, {
      lid: 6,
      uid: 1,
      time: new Date(2012, 4, 16, 9, 8, 6).getTime(),
      text: 'This electronic review, currently called Hawk-Eye, is available at a limited number of high-level ATP and WTA tournaments.'
    }, {
      lid: 7,
      uid: 3,
      time: new Date(2012, 4, 16, 9, 9, 6).getTime(),
      text: ' Players have unlimited opportunities.'
    }, {
      lid: 8,
      uid: 5,
      time: new Date(2012, 4, 16, 9, 9, 9).getTime(),
      text: 'The rules of tennis have not changed much since the 1890s.'
    }, {
      lid: 9,
      uid: 5,
      time: util.now(),
      text: 'The modern game of tennis originated in Birmingham, England in the late 19th century as "lawn tennis" which has close connections to various field/lawn games as well as to the ancient game of real tennis. '
    }, {
      lid: 10,
      uid: 2,
      time: util.now(),
      text: 'Barack Obama is the president of the United States of America right now.'
    }, {
      lid: 11,
      uid: 1,
      time: util.now(),
      text: 'And he will continue to be president, because the banking community likes him and are making things easy by presenting Mitt Romney.'
    }, {
      lid: 12,
      uid: 3,
      time: util.now(),
      text: 'What do you think the Canadians think about this?'
    }
  ];

  module.exports = {
    users: users,
    log: log
  };

}).call(this);
